config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :views
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'home#index'

get 'index' => "home#index"

resources :archives do
    collection do
      get :index, :add_files, :import_txt, :batchupload, :cat, :batch, :new, :advanced_search, :test, :search, :letter, :county, :city, :category, :edit, :missionary, :edit_manuscripts, :manuscripts, :manuscripts_city, :genealogy,:genealogy_county,:guide
      post  :save, :import, :import_new, :searchlist, :search, :advanced_search, :editsave, :batchsave
    end
  end 

resources :about do
    collection do
      get :about, :bookshelf, :stamp, :genealogy, :history, :national, :import_data
      post :import
    end
  end   
 
 resources :missionary do
   collection do
      get :import_file
      post :import 
   end  
 end

  resources :manuscript do
   collection do
      get :import_file
      post :import, :save
   end  
 end

  resources :genealogy do
   collection do
      get :import_file
      post :import 
   end  
 end

 resources :permit do
    collection do
      get :index
      post :save
    end
  end  

 resources :contact do
    collection do
      get :index, :support
      
    end
  end  
end

app/models/acategory.rb
class Acategory < ApplicationRecord
end

app/models/acity.rb
class Acity < ApplicationRecord
end

app/models/acounty.rb
class Acounty < ApplicationRecord
end

app/models/archive.rb
class Archive < ApplicationRecord
	paginates_per 30
	max_paginates_per 100
	max_pages 500
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/genealogy.rb
class Genealogy < ApplicationRecord
end

app/models/guide.rb
class Guide < ApplicationRecord
end

app/models/manuscript.rb
class Manuscript < ApplicationRecord
end

app/models/missionary.rb
class Missionary < ApplicationRecord
end

app/models/permit.rb
class Permit < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/stamp.rb
class Stamp < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_archive.rb
class UserArchive < ApplicationRecord
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/permit_controller.rb
class PermitController < ApplicationController
include ApplicationHelper

 def index

   @allp = Permit.all
   @allu = User.all

   @uname = ['']
   @allu.each do |t|
      @uname << t.email
    end

   @all_levels = ["Admin",  "Guest"]
   @all_levels_val = ["1", "9"]

 end

 def save
    u = params["uname"]
    role = params["role"]
    all_levels = ["Admin",  "Guest"]
    all_levels_val = ["1", "9"]
    pos = all_levels.find_index(role)
    if (!u.empty?)
     p = Permit.new
     p.email = u
     p.level = all_levels_val[pos]
     p.save!
    end	
 end	
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/genealogy_helper.rb
module GenealogyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/permit_helper.rb
module PermitHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/permit/index.html.erb
<% #if (@approve_access) %>

<div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="panel-title">User Accounts</h5>
    </div>
    <div class="card-body">
  
	<h6 class="panel-title">Update User Accounts</h6>
	<%= form_tag(save_permit_index_path, :enctype =>"multipart/form-data") do  %>
    <div class="row ml-1">
      <div class="field">
      Email:
     <%= select_tag "uname", options_for_select(@uname)  %>
      </div>
    </div>

    <div class="row ml-1">
      <div class="field">
      Role:
     <%= select_tag "role", options_for_select(@all_levels)  %>
      </div>
    </div>

    <div class="actions">
        <%= submit_tag 'Assign Role' %>
    </div>
   <% end %>
   <hr>
    <%
        @allp.each do |one_p|
        pos = one_p.email.index("@")
		pos = pos- 1
		level_pos = @all_levels_val.find_index(one_p.level.to_s)
		
	%>
		<p><b><%#= one_p.email[0..pos] %>
    <%= one_p.email %>  
    </b><br>
			<% if (one_p.level ==0) %>
				Super Admin
			<% else %>
			  <%= @all_levels[level_pos] %>	
			<% end %>	
		</p>
	<% end %>
	
    </div>
</div>     
   
<% #end %>

app/views/permit/save.html.erb
Role saved