config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :views
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'home#index'

get 'index' => "home#index"

resources :archives do
    collection do
      get :index, :add_files, :import_txt, :batchupload, :cat, :batch, :new, :advanced_search, :test, :search, :letter, :county, :city, :category, :edit, :missionary, :edit_manuscripts, :manuscripts, :manuscripts_city, :genealogy,:genealogy_county,:guide
      post  :save, :import, :import_new, :searchlist, :search, :advanced_search, :editsave, :batchsave
    end
  end 

resources :about do
    collection do
      get :about, :bookshelf, :stamp, :genealogy, :history, :national, :import_data
      post :import
    end
  end   
 
 resources :missionary do
   collection do
      get :import_file
      post :import 
   end  
 end

  resources :manuscript do
   collection do
      get :import_file
      post :import, :save
   end  
 end

  resources :genealogy do
   collection do
      get :import_file
      post :import 
   end  
 end

 resources :permit do
    collection do
      get :index
      post :save
    end
  end  

 resources :contact do
    collection do
      get :index, :support
      
    end
  end  
end

app/models/acategory.rb
class Acategory < ApplicationRecord
end

app/models/acity.rb
class Acity < ApplicationRecord
end

app/models/acounty.rb
class Acounty < ApplicationRecord
end

app/models/archive.rb
class Archive < ApplicationRecord
	paginates_per 30
	max_paginates_per 100
	max_pages 500
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/genealogy.rb
class Genealogy < ApplicationRecord
end

app/models/guide.rb
class Guide < ApplicationRecord
end

app/models/manuscript.rb
class Manuscript < ApplicationRecord
end

app/models/missionary.rb
class Missionary < ApplicationRecord
end

app/models/permit.rb
class Permit < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/stamp.rb
class Stamp < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_archive.rb
class UserArchive < ApplicationRecord
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/permit_helper.rb
module PermitHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ernies Michigan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ernies Michigan</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div >
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container-fluid">
            <a href="/" class="navbar-brand">
              <% url = image_url('https://ernie-tpics.s3.amazonaws.com/ernie.png') %>
              <%= image_tag(url, alt: "Home Page", size:"90x60") %>
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Archives</a>
                        <div class="dropdown-menu">
                            <%= link_to 'Browse', search_archives_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'Advanced Search', advanced_search_archives_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                             <%= link_to 'Missionary Letters', missionary_archives_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                             <%= link_to 'Manuscripts', manuscripts_archives_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                             <%= link_to 'Genealogy', genealogy_archives_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                             <%= link_to 'Guide to Listing', guide_archives_path, class: 'nav-link' %>
                        </div>
                    </li>
                     <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">About</a>
                        <div class="dropdown-menu">
                            <%= link_to 'About Ernie', about_about_index_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'Ernie''s Bookshelf', bookshelf_about_index_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'MI Stamp Clubs', stamp_about_index_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'MI Genealogy Clubs', genealogy_about_index_path, class: 'nav-link' %>
                            <a href="#"class="dropdown-item"></a>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'MI History Societies', history_about_index_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'National Societies', national_about_index_path, class: 'nav-link' %>
                          
                        </div>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Contact", contact_index_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Support Our Work", support_contact_index_path, class: 'nav-link' %>
                    </li>
                    
                    
                </ul>
                <ul class="nav navbar-nav ms-auto">
                    <li class="nav-item dropdown">
                       <% 
                        if user_signed_in? %>
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><%= current_user.email %></a>
                         <div class="dropdown-menu dropdown-menu-end">
                             <%= link_to 'My Account', edit_user_registration_path, class: 'nav-link' %>
                            <div class="dropdown-divider"></div>
                             <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                        </div>
                       <% else %>
                          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
                       <% end %> 
                       
                    </li>
                </ul>
            </div>
        </div>
    </nav>    
</div>
</body>
</html>

app/views/shared/_searchbar.html.erb
<%= form_tag(search_archives_path, :enctype =>"multipart/form-data") do %>
  <div class="form-group">
    
      <%= search_field_tag 'searchterm', value="" ,size: 60 %><button type="submit" class="btn btn-primary" style="margin-left: 6px;">Search</button> 
  </div>
 
<% end %>