config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :views
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'home#index'

get 'index' => "home#index"

resources :archives do
    collection do
      get :index, :add_files, :import_txt, :batchupload, :cat, :batch, :new, :advanced_search, :test, :search, :letter, :county, :city, :category, :edit, :missionary, :edit_manuscripts, :manuscripts, :manuscripts_city, :genealogy,:genealogy_county,:guide
      post  :save, :import, :import_new, :searchlist, :search, :advanced_search, :editsave, :batchsave
    end
  end 

resources :about do
    collection do
      get :about, :bookshelf, :stamp, :genealogy, :history, :national, :import_data
      post :import
    end
  end   
 
 resources :missionary do
   collection do
      get :import_file
      post :import 
   end  
 end

  resources :manuscript do
   collection do
      get :import_file
      post :import, :save
   end  
 end

  resources :genealogy do
   collection do
      get :import_file
      post :import 
   end  
 end

 resources :permit do
    collection do
      get :index
      post :save
    end
  end  

 resources :contact do
    collection do
      get :index, :support
      
    end
  end  
end

app/models/archive.rb
class Archive < ApplicationRecord
	paginates_per 30
	max_paginates_per 100
	max_pages 500
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
skip_before_action :verify_authenticity_token
protect_from_forgery with: :null_session
include ApplicationHelper

def index
	
end

def cat
  str = ""

  Archive.all.each do |a| 
    if ((a.category.nil?) || (a.category.eql? "") )
      str =  a.category1 if (!a.category1.nil?)
      str = str + ", "+ a.category2 if (!a.category2.nil?)
      str = str + ", "+ a.category3 if (!a.category3.nil?)
      str = str + ", "+ a.category4 if (!a.category4.nil?)
      str = str + ", "+ a.category5 if (!a.category5.nil?)
      str = str + ", "+ a.category6 if (!a.category6.nil?)
      str = str + ", "+ a.category7 if (!a.category7.nil?)
      str = str + ", "+ a.category8 if (!a.category8.nil?)
      str = str + ", "+ a.category9 if (!a.category9.nil?)
      str = str + ", "+ a.category10 if (!a.category10.nil?)
      str = str + ", "+ a.category11 if (!a.category11.nil?)
      str = str + ", "+ a.category12 if (!a.category12.nil?)
      str = str + ", "+ a.category13 if (!a.category13.nil?)
      str = str + ", "+ a.category14 if (!a.category14.nil?)
      str = str + ", "+ a.category15 if (!a.category15.nil?)
      str = str + ", "+ a.category16 if (!a.category16.nil?)
      str = str + ", "+ a.category17 if (!a.category17.nil?)
      str = str + ", "+ a.category18 if (!a.category18.nil?)
      str = str + ", "+ a.category19 if (!a.category19.nil?)
      str = str + ", "+ a.category20 if (!a.category20.nil?)
      a.category = str
      a.save!
    end
  end  
       
end  
def new
	@acategory = Acategory.all.order(:name)
	@acounty = Acounty.all.order(:name)
	@acity = Acity.all.order(:name)
end	

def edit
	@acategory = Acategory.all.order(:name)
	@acounty = Acounty.all.order(:name)
	@acity = Acity.all.order(:name)
	@county_list = concat_county 
    @city_list = concat_city
    @category_list = concat_category
end	

def editsave
  id = params["id"]

  a = Archive.where("id=?",id).first
  a.fname = params["fname"]
  a.path = params["path"]
  a.caption = params["title"]
  a.pyear = params["pyear"]
  a.pdate = params["pdate"]
  a.pic_status = params["pic_status"]
  a.cover_page = params["cover_page"]
  a.price = params["pprice"]
  a.cost = params["pcost"]
  a.ptype = params["pid"]
    
    
    a.county1 = params["county1"]
    a.county2 = params["county2"]
    a.county3 = params["county3"]
    a.county4 = params["county4"]
    a.county5 = params["county5"]
    a.county6 = params["county6"]
    a.county7 = params["county7"]
    a.county8 = params["county8"]
    a.county9 = params["county9"]
    a.county10 = params["county10"]
    a.county = a.county1 + "," + a.county2 + "," + a.county3 + "," + a.county4 + "," + a.county5 
    a.county =  a.county + "," + a.county6 + "," + a.county7 + "," + a.county8 + "," + a.county9 + "," + a.county10
    
    a.city1 = params["city1"]
    a.city2 = params["city2"]
    a.city3 = params["city3"]
    a.city4 = params["city4"]
    a.city5 = params["city5"]
    a.city6 = params["city6"]
    a.city7 = params["city7"]
    a.city8 = params["city8"]
    a.city9 = params["city9"]
    a.city10 = params["city10"] 
    a.city11 = params["city11"]
    a.city = a.city1 + "," + a.city2 + "," + a.city3 + "," + a.city4 + "," + a.city5 + ","
    a.city = a.city + a.city6 + "," + a.city7 + "," + a.city8 + "," + a.city9 + "," + a.city10
 
    
    a.category1 = params["cat1"]
    a.category2 = params["cat2"]
    a.category3 = params["cat3"]
    a.category4 = params["cat4"]
    a.category5 = params["cat5"]
    a.category6 = params["cat6"]
    a.category7 = params["cat7"]
    a.category8 = params["cat8"]
    a.category9 = params["cat9"]
    a.category10 = params["cat10"]
    a.category11 = params["cat11"]
    a.category12 = params["cat12"]
    a.category13 = params["cat13"]
    a.category14 = params["cat14"]
    a.category15 = params["cat15"]
    a.category16 = params["cat16"]
    a.category17 = params["cat17"]
    a.category18 = params["cat18"]
    a.category19 = params["cat19"]
    a.category20 = params["cat20"]
    a.category = a.category1 + "," + a.category2 + "," + a.category3 + "," + a.category4 + ","
    a.category = a.category + "," + a.category5 + "," + a.category6 + "," + a.category7 + "," + a.category8 + ","
    a.category = a.category + "," + a.category9 + "," + a.category10 + "," + a.category11 + "," + a.category12 + ","
    a.category = a.category + "," + a.category13 + "," + a.category14 + "," + a.category15 + "," + a.category16 + ","
    a.category = a.category + "," + a.category17 + "," + a.category18 + "," + a.category19 + "," + a.category20 
    
    
  a.save!
end  

def save

  
	#upload pic
	#base_url = "https://ernie-tpics.s3.amazonaws.com/tpics/" 
  # Make an object in your bucket for your upload
    obj = S3_BUCKET.objects[params[:file].original_filename]

    # Upload the file
    obj.write(
      bucket: ENV['S3_BUCKET'],
      file: params[:file],
      acl: :public_read
    )

	fname = params[:file].original_filename
  
	a = Archive.new
	a.fname = fname
  a.path = ""
	a.caption = params["title"]
	a.pyear = params["pyear"]
	a.pdate = params["pdate"]
	a.pic_status = params["pic_status"]
  if a.pic_status.nil?
    a.pic_status = false
  end  
	a.cover_page = params["cover_page"]
	a.price = params["pprice"]
	a.cost = params["pcost"]
    
    a.county1 = params["county1"]
    a.county2 = params["county2"]
    a.county3 = params["county3"]
    a.county4 = params["county4"]
    a.county5 = params["county5"]
    a.county6 = params["county6"]
    a.county7 = params["county7"]
    a.county8 = params["county8"]
    a.county9 = params["county9"]
    a.county10 = params["county10"]
    a.county = a.county1 + "," + a.county2 + "," + a.county3 + "," + a.county4 + "," + a.county5 
    a.county =  a.county + "," + a.county6 + "," + a.county7 + "," + a.county8 + "," + a.county9 + "," + a.county10
    
    a.city1 = params["city1"]
    a.city2 = params["city2"]
    a.city3 = params["city3"]
    a.city4 = params["city4"]
    a.city5 = params["city5"]
    a.city6 = params["city6"]
    a.city7 = params["city7"]
    a.city8 = params["city8"]
    a.city9 = params["city9"]
    a.city10 = params["city10"] 
    a.city11 = params["city11"]
    a.city = a.city1 + "," + a.city2 + "," + a.city3 + "," + a.city4 + "," + a.city5 + ","
    a.city = a.city + a.city6 + "," + a.city7 + "," + a.city8 + "," + a.city9 + "," + a.city10
 
    
    a.category1 = params["cat1"]
    a.category2 = params["cat2"]
    a.category3 = params["cat3"]
    a.category4 = params["cat4"]
    a.category5 = params["cat5"]
    a.category6 = params["cat6"]
    a.category7 = params["cat7"]
    a.category8 = params["cat8"]
    a.category9 = params["cat9"]
    a.category10 = params["cat10"]
    a.category11 = params["cat11"]
    a.category12 = params["cat12"]
    a.category13 = params["cat13"]
    a.category14 = params["cat14"]
    a.category15 = params["cat15"]
    a.category16 = params["cat16"]
    a.category17 = params["cat17"]
    a.category18 = params["cat18"]
    a.category19 = params["cat19"]
    a.category20 = params["cat20"]
   # a.category = a.category1 + "," + a.category2 + "," + a.category3 + "," + a.category4 + ","
   # a.category = a.category + "," + a.category5 + "," + a.category6 + "," + a.category7 + "," + a.category8 + ","
   # a.category = a.category + "," + a.category9 + "," + a.category10 + "," + a.category11 + "," + a.category12 + ","
   # a.category = a.category + "," + a.category13 + "," + a.category14 + "," + a.category15 + "," + a.category16 + ","
   # a.category = a.category + "," + a.category17 + "," + a.category18 + "," + a.category19 + "," + a.category20 
    
    
	a.save!
  id = a.id

  params["id"] = id
  @a = Archive.where("id=?",id).first
  
  #save the current user

  u = UserArchive.new
  u.email = current_user.email
  u.a_id = id 
  u.save!
  
end


	
def show
end
	

def advanced_search

   	@acategory = Acategory.all.order(:name)
	@acounty = Acounty.all.order(:name)
	@acity = Acity.all.order(:name)
    @connector = ['AND', 'OR']
    
    @county = params["county"]
    @county1 = params["county1"]
    @county2 = params["county2"]
    @county3 = params["county3"]
    
    @county = "" if @county.nil?
    @county1 = "" if @county1.nil?
    @county2 = "" if @county2.nil?
    @county3 = "" if @county3.nil?

    @city = params["city"]
    @city1 = params["city1"]
    @city2 = params["city2"]
    @city3 = params["city3"]
    
    @city = "" if @city.nil?
    @city1 = "" if @city1.nil?
    @city2 = "" if @city2.nil?
    @city3 = "" if @city3.nil?

    @con011 = params["con011"]
    @con111 = params["con111"]
    @con1 = params["con1"]
    @con11 = params["con11"]
    @con12 = params["con12"]
    @con13 = params["con13"]

    @con2 = params["con2"]
    @con21 = params["con21"]
    @con22 = params["con22"]
    @con23 = params["con23"]

    @con3 = params["con3"]
    @con31 = params["con31"]
    @con32 = params["con32"]
    @con33 = params["con33"]
    @con34 = params["con34"]
    @con35 = params["con35"]
    @con36 = params["con36"]
    @con37 = params["con37"]
    @con38 = params["con38"]

    @category = params["category"]
    @category1 = params["category1"]
    @category2 = params["category2"]
    @category3 = params["category3"]
    @category4 = params["category4"]
    @category5 = params["category5"]
    @category6 = params["category6"]
    @category7 = params["category7"]
    @category8 = params["category8"]
    @category9 = params["category9"]
  
    
    @category = "" if @category.nil?
    @category1 = "" if @category1.nil?
    @category2 = "" if @category2.nil?
    @category3 = "" if @category3.nil?
    @category4 = "" if @category4.nil?
    @category5 = "" if @category5.nil?
    @category6 = "" if @category6.nil?
    @category7 = "" if @category7.nil?
    @category8 = "" if @category8.nil?
    @category9 = "" if @category9.nil?
   
    
    itemid = params["itemid"]
    itemid_new = params["itemid_new"]
    @searchterm = params["searchterm"]

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/add_files.html.erb
<div class="container">
<h4> Adding Files...done </h4>
</div>

app/views/archives/batch.html.erb
<div class="container">
  
<h4> Import List </h4>

<%= form_tag("import", :enctype =>"multipart/form-data") do %>
   <div class="row">
     <div class="field">
       <%= label_tag :file %>
       <%= file_field_tag :file,  :required => true  %>
     </div>
   </div>

   <div class="row">
   <div class="actions">
      <%= submit_tag 'Next' %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %> 
   </div>

<% end %>   
</div>

app/views/archives/batchsave.html.erb
<div class="container">
	<%
	folder = params["folder"]
	 Dir[folder].each do |file_name|
	 	%>
	 	<%= file_name %>
	 <%	
  next if File.directory? file_name 
 end
	%>
</div>	

app/views/archives/edit_manuscripts.html.erb
<% id = params["id"] %>
<% 
if (id.eql? "0")
  @one = Manuscript.new
else
 @one = Manuscript.where("id=?",id)
@one = @one.first 
end

%>
<div class="container">

  <h4> Edit Manuscript</h4> 
 
  <%= form_tag(save_manuscript_index_path, :enctype =>"multipart/form-data") do %>

  <div class="card" style="width: 45rem; padding-left: 10px;">
  <p>Mnum (Private or Public) <br><input name="mnum" value="<%= @one.mnum %>"></p>   
  <p>Town <br><input name="town" value="<%= @one.town %>" size=50></p>  
    <p>Cover/Stampless<br><input name="c_or_s" type="text" value="<%=@one.c_or_s%>"></p>
  
  <p>STE<br> <input type="text" name="ste" value="<%= @one.ste %>"></p>
  <p>Date<br><input type="text" name="dd" value="<%= @one.dd %>"></p>
  <p>Year<br><input type="text" name="yr" value="<%= @one.yr %>"></p>
  <p>Marking<br><input type="text" name="marking" value="<%= @one.marking %>"><br></p>
  <p>County<br><input type="text" name="county" value="<%= @one.county %>"></p>
  <p>EMI?<br><input type="text" name="emi" value="<%= @one.emi %>"></p>
  <p>Parent ID<br><input type="text" name="new_id" value="<%= @one.new_id %>"></p>
  
  </div>
  
  
  <div class="form-group" style="padding-top: 20px">
    <div class="col-sm-offset-2 col-sm-10">
      <%= hidden_field_tag 'id',id %>
      <button type="submit" class="btn btn-primary">Update</button> 
      <%#<button type="Reset" class="btn btn-secondary">Reset Form</button> %>
    </div>
  </div>

  <% end %>
</div>

app/views/archives/genealogy_county.html.erb
<% county = params["county"] %>
<div class="container">
<h4>Michigan Genealogy Surname list by County</h4>

<p><strong>County: <%= county %></strong> <br><%= link_to "Back to Counties" , genealogy_archives_path%></p>
 
<div class="row" style="background-color: #e3e3e3;">
	<div class="col">Name</div>
	<div class="col">Town</div>
	<div class="col">Date</div>
	<div class="col">On Ernies Michigan?</div>
	

</div>
<%
  g_list = Genealogy.where("county=?",county)
  g_list.each do |g|
%>
<div class="row">
	<div class="col"><%= g.name %></div>
	<div class="col"><%= g.town %></div>
	<div class="col"><%= g.dt %></div>
	<div class="col"><% if (g.emi==1) %>Yes<% else %>No<% end %>
	<% if (g.emi==1) %><%= link_to "View",advanced_search_archives_path(:searchterm => g.dt)%><%end%>
		
	</div>
</div>
<%  	
  end	
%>
</div>

app/views/archives/import_new.html.erb
<div class="container">
<h4> Import List...done </h4>
</div>

app/views/archives/letter.html.erb
<% str = params["s"]
 %>
<div class ="container">
   <% b = params["b"] 
     if (b.eql? "1") %>
    <p align=left> <%= link_to "Back to Search Results", search_archives_path(:back => 1, :page => $lastpage, :str => str)  %>
     </p>   
    <% 
      end
       id = @a.id
       if (id.nil?)
         $n = $archivelist.where("id > ?", id).first 
         $p = $archivelist.where("id < ?", id).last
       else
         $n = $p = nil
       end    
    %>
    <p align=right>   
    <%   if (!$p.nil?)
    %>
     <%= link_to "<< Prev", letter_archives_path(:id => id, :next=>0, :prev=>1)  %> 
    <% end %>
    <%   if (!$p.nil? && !$n.nil?) %>
     | 
    <% end %>
    <% if (!$n.nil?) %>
	 <%= link_to "Next >> ", letter_archives_path(:id => id, :next=>1, :prev=>0) %>
    <% end %>  
    </p>
	<p><%= @a.caption%> 
    <% access_level = check_current_access %>
    <% if (access_level==1) %>
              <p> <%= link_to "Edit", edit_archives_path(:id =>id)  %></p>
            <% end %> </p> 
	<% base_url = "https://ernie-tpics.s3.amazonaws.com/" 
  ppath = @a.path

  if (ppath.eql? "Tpics")
    ppath = "tpics"
  end 
    
	if (@a.fname.nil?)
    fname_url = "ernie.png"
   elsif (ppath.length>0)
    fname_url = base_url+ ppath + "/" + @a.fname 
   else 
    fname_url = base_url + @a.fname  
   end  
	 %>
	<% url = image_url(fname_url)%>
  <%
  #fname_url_encoded = fname_url.gsub!('%20', ' ')
  %> 
	<p align="left">
    <div id="seadragon-viewer" style="width:1000px; height:600px;"></div>
  <%#= image_tag(url, style: 'height:60%;width:60%;') %>
    
  </p>
	<p><b>Year:</b> <%= @a.pyear %> <br>
        <b>Date:</b> <%= @a.pdate %> <br>

        <b>County:</b> 
    	   <% if ((!@a.county1.eql? "") && (!@a.county1.eql? nil)) %>
          <%= link_to @a.county1, search_archives_path(:county => @a.county1)  %>
        <%end%> 
        <% if ((!@a.county2.eql? "") && (!@a.county2.eql? nil)) %> 
          , <%= link_to @a.county2, search_archives_path(:county => @a.county2)  %> 
        <%end%>
        <% if ((!@a.county3.eql? "") && (!@a.county3.eql? nil)) %>
          , <%= link_to @a.county3, search_archives_path(:county => @a.county3)  %>
        <%end%> 
         <% if ((!@a.county4.eql? "") && (!@a.county4.eql? nil)) %>
          , <%= link_to @a.county4, search_archives_path(:county => @a.county4)  %>
        <%end%> 
        <% if ((!@a.county5.eql? "") && (!@a.county5.eql? nil)) %>
          , <%= link_to @a.county5, search_archives_path(:county => @a.county5)  %> 
        <%end%>
        <% if ((!@a.county6.eql? "") && (!@a.county6.eql? nil)) %>
          , <%= link_to @a.county6, search_archives_path(:county => @a.county6)  %>
        <%end%> 
         <% if ((!@a.county7.eql? "") && (!@a.county7.eql? nil)) %>
          , <%= link_to @a.county7, search_archives_path(:county => @a.county7)  %>
        <%end%> 
        <% if ((!@a.county8.eql? "") && (!@a.county8.eql? nil)) %>
          , <%= link_to @a.county8, search_archives_path(:county => @a.county8)  %> 
        <%end%>
        <% if ((!@a.county9.eql? "") && (!@a.county9.eql? nil)) %>
          , <%= link_to @a.county9, search_archives_path(:county => @a.county9)  %>  
        <%end%> 
        <% if ((!@a.county10.eql? "") && (!@a.county10.eql? nil)) %>
         , <%= link_to @a.county10, search_archives_path(:county => @a.county10)  %>  
        <%end%> 
    	 
    	  <br>
    	<b>City:</b> 
    	  
        <% if ((!@a.city1.eql? "") && (!@a.city1.eql? nil)) %>
         <%= link_to @a.city1, search_archives_path(:city => @a.city1)  %>  
        <%end%> 
        <% if ((!@a.city2.eql? "") && (!@a.city2.eql? nil)) %>
         , <%= link_to @a.city2, search_archives_path(:city => @a.city2)  %>  
        <%end%> 
        <% if ((!@a.city3.eql? "") && (!@a.city3.eql? nil)) %>
         , <%= link_to @a.city3, search_archives_path(:city => @a.city3)  %>  
        <%end%> 
    	  <% if ((!@a.city4.eql? "") && (!@a.city4.eql? nil)) %>
         , <%= link_to @a.city4, search_archives_path(:city => @a.city4)  %>  
        <%end%> 
        <% if ((!@a.city5.eql? "") && (!@a.city5.eql? nil)) %>
         , <%= link_to @a.city5, search_archives_path(:city => @a.city5)  %>  
        <%end%> 
        <% if ((!@a.city6.eql? "") && (!@a.city6.eql? nil)) %>
         , <%= link_to @a.city6, search_archives_path(:city => @a.city6)  %>  
        <%end%> 
        <% if ((!@a.city7.eql? "") && (!@a.city7.eql? nil)) %>
         , <%= link_to @a.city7, search_archives_path(:city => @a.city7)  %>  
        <%end%> 
        <% if ((!@a.city8.eql? "") && (!@a.city8.eql? nil)) %>
         , <%= link_to @a.city8, search_archives_path(:city => @a.city8)  %>  
        <%end%>
        <% if ((!@a.city9.eql? "") && (!@a.city9.eql? nil)) %>
         , <%= link_to @a.city9, search_archives_path(:city => @a.city9)  %>  
        <%end%>  
      
        <br>
    	<b>Category:</b> 
       
    	 <% if ((!@a.category1.eql? "") && (!@a.category1.eql? nil)) %>  <%= link_to @a.category1, search_archives_path(:category => @a.category1)  %> <%end%>
    	 <% if ((!@a.category2.eql? "") && (!@a.category2.eql? nil)) %>,  <%= link_to @a.category2, search_archives_path(:category => @a.category2)  %>  <%end%> 
    	   <% if ((!@a.category3.eql? "") && (!@a.category3.eql? nil)) %>, <%= link_to @a.category3, search_archives_path(:category => @a.category3)  %> <%end%> 
    	   <% if ((!@a.category4.eql? "") && (!@a.category4.eql? nil)) %>, <%= link_to @a.category4, search_archives_path(:category => @a.category4)  %> <%end%> 
    	   <% if ((!@a.category5.eql? "") && (!@a.category5.eql? nil)) %>, <%= link_to @a.category5, search_archives_path(:category => @a.category5)  %> <%end%> 
    	  <% if ((!@a.category6.eql? "") && (!@a.category6.eql? nil)) %>, <%= link_to @a.category6, search_archives_path(:category => @a.category6)  %> <%end%> 
    	  <% if ((!@a.category7.eql? "") && (!@a.category7.eql? nil)) %>, <%= link_to @a.category7, search_archives_path(:category => @a.category7)  %> <%end%> 
    	   <% if ((!@a.category8.eql? "") && (!@a.category8.eql? nil)) %>, <%= link_to @a.category8, search_archives_path(:category => @a.category8)  %> <%end%> 
    	  <% if ((!@a.category9.eql? "") && (!@a.category9.eql? nil)) %>, <%= link_to @a.category9, search_archives_path(:category => @a.category9)  %> <%end%> 
    	  <% if ((!@a.category10.eql? "") && (!@a.category10.eql? nil)) %>, <%= link_to @a.category10, search_archives_path(:category => @a.category10)  %> <%end%> 
    	  <% if ((!@a.category11.eql? "") && (!@a.category11.eql? nil)) %>, <%= link_to @a.category11, search_archives_path(:category => @a.category11)  %> <%end%> 
    	  <% if ((!@a.category12.eql? "") && (!@a.category12.eql? nil)) %>, <%= link_to @a.category12, search_archives_path(:category => @a.category12)  %> <%end%> 
    	   <% if ((!@a.category13.eql? "") && (!@a.category13.eql? nil)) %>, <%= link_to @a.category13, search_archives_path(:category => @a.category13)  %> <%end%> 
    	  <% if ((!@a.category14.eql? "") && (!@a.category14.eql? nil)) %>, <%= link_to @a.category14, search_archives_path(:category => @a.category14)  %> <%end%> 
    	  <% if ((!@a.category15.eql? "") && (!@a.category15.eql? nil)) %>, <%= link_to @a.category15, search_archives_path(:category => @a.category15)  %> <%end%> 
    	  <% if ((!@a.category16.eql? "") && (!@a.category16.eql? nil)) %>, <%= link_to @a.category16, search_archives_path(:category => @a.category16)  %> <%end%> 
    	  <% if ((!@a.category17.eql? "") && (!@a.category17.eql? nil)) %>, <%= link_to @a.category17, search_archives_path(:category => @a.category17)  %> <%end%> 
    	  <% if ((!@a.category18.eql? "") && (!@a.category18.eql? nil)) %>, <%= link_to @a.category18, search_archives_path(:category => @a.category18)  %> <%end%> 
    	   <% if ((!@a.category19.eql? "") && (!@a.category19.eql? nil)) %>, <%= link_to @a.category19, search_archives_path(:category => @a.category19)  %> <%end%> 
    	  <% if ((!@a.category20.eql? "") && (!@a.category20.eql? nil)) %>, <%= link_to @a.category20, search_archives_path(:category => @a.category20)  %> <%end%> 
    	  
    	  <br>
         <%
          if (@a.old_id>0)
            check_id = @a.old_id
          else
            check_id = @a.id
          end 
              
            associated = Archive.where("ptype=?",check_id)
            associated_count = associated.count
            if (associated_count==0 && @a.ptype != nil && @a.ptype >0)
              associated = Archive.where("ptype=?",@a.ptype)
              associated_count = associated.count
            end 
           
        %>
       
    	  <%
          
          num = 1 
          %>
          <b>Associated Pages: </b><%=associated_count%> <br>
          <% associated.each do |assoc| %>

          <p><%=num%>. <%=assoc.caption %>  <%= link_to "Read More..", letter_archives_path(:id => assoc.id)  %></p>
          <% num= num+1 %>
        <%end
        
        %>  
     </p>

</div>


<script src="//openseadragon.github.io/openseadragon/openseadragon.min.js"></script>

<script type="text/javascript">
var viewer = OpenSeadragon({
  id: "seadragon-viewer",
  prefixUrl: "//openseadragon.github.io/openseadragon/images/",
  showRotationControl: true,
  tileSources: {
        type: 'image',
        url:  '<%= fname_url %>'
    }
});
</script>

app/views/archives/old_new.html.erb
<div class="container">
  
<h4> Import List </h4>

<%= form_tag("import", :enctype =>"multipart/form-data") do %>
   <div class="row">
     <div class="field">
       <%= label_tag :file %>
       <%= file_field_tag :file,  :required => true  %>
     </div>
   </div>

   <div class="row">
   <div class="actions">
      <%= submit_tag 'Next' %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %> 
   </div>

<% end %>   
</div>

app/views/archives/save_manuscript.html.erb
<div class="container">
	<p>Manuscript saved successfully...</p>
</div>	

app/views/archives/show.html.erb
Oops...something went wrong

app/views/archives/test.html.erb
<% fname_url = "https://ernie-tpics.s3.amazonaws.com/tpics/02-16-2009-10-48-03-609.jpg" %>
<% url = image_url(fname_url)%>
<div id="seadragon-viewer" style="width:800px; height:600px;"></div>
<script src="//openseadragon.github.io/openseadragon/openseadragon.min.js"></script>

<script type="text/javascript">
var viewer = OpenSeadragon({
  id: "seadragon-viewer",
  prefixUrl: "//openseadragon.github.io/openseadragon/images/",
  tileSources: {
        type: 'image',
        url:  '<%= fname_url %>'
    }
});
</script>	