config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :views
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'home#index'

get 'index' => "home#index"

resources :archives do
    collection do
      get :index, :add_files, :import_txt, :batchupload, :cat, :batch, :new, :advanced_search, :test, :search, :letter, :county, :city, :category, :edit, :missionary, :edit_manuscripts, :manuscripts, :manuscripts_city, :genealogy,:genealogy_county,:guide
      post  :save, :import, :import_new, :searchlist, :search, :advanced_search, :editsave, :batchsave
    end
  end 

resources :about do
    collection do
      get :about, :bookshelf, :stamp, :genealogy, :history, :national, :import_data
      post :import
    end
  end   
 
 resources :missionary do
   collection do
      get :import_file
      post :import 
   end  
 end

  resources :manuscript do
   collection do
      get :import_file
      post :import, :save
   end  
 end

  resources :genealogy do
   collection do
      get :import_file
      post :import 
   end  
 end

 resources :permit do
    collection do
      get :index
      post :save
    end
  end  

 resources :contact do
    collection do
      get :index, :support
      
    end
  end  
end

app/models/acategory.rb
class Acategory < ApplicationRecord
end

app/models/acity.rb
class Acity < ApplicationRecord
end

app/models/acounty.rb
class Acounty < ApplicationRecord
end

app/models/archive.rb
class Archive < ApplicationRecord
	paginates_per 30
	max_paginates_per 100
	max_pages 500
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/genealogy.rb
class Genealogy < ApplicationRecord
end

app/models/guide.rb
class Guide < ApplicationRecord
end

app/models/manuscript.rb
class Manuscript < ApplicationRecord
end

app/models/missionary.rb
class Missionary < ApplicationRecord
end

app/models/permit.rb
class Permit < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/stamp.rb
class Stamp < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_archive.rb
class UserArchive < ApplicationRecord
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

def import_data
end

def import
  uploaded_csv = params[:file]  
  csv_text = File.read(uploaded_csv)

  csv = CSV.parse(csv_text, :headers => true)
  csv.each do |row|
    row_hash = row.to_hash
    s= Stamp.new
    s.cName = row_hash["1"]
    s.pName = row_hash["2"]
    s.Address = row_hash["3"]
    s.MTimes = row_hash["4"]
    s.Waddr = row_hash["5"]
    s.Com = row_hash["6"]
    s.save!
  end 
end  

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/permit_helper.rb
module PermitHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/about/about.html.erb
<%
bad_a = Archive.where("pdate LIKE '%/%'")
 bad_a.each do |a| 
 a.pdate = a.caption[0..9]
 a.save!
end 
%>
<div class="container">
	<h2>About Ernie's Michigan Historical Archives</h2>
	<p>I have been a stamp collector since I was 10 years old. The husband of one of my mother's coworkers was a stamp collector. He gave me my first stamp album and a packet of stamps. I was hooked and have been a collector ever since.</p>

<p>When I moved to Michigan in 1972 I branched out to include the area of cover (letter) collecting. A cover is an envelope with or without the accompanying letter. In the case of stampless (folded) covers the address and postal information was written on a part of the letter after it was folded up, sealed, and ready to mail.</p>

<p>Each letter is unique in that it was written from a sender to a recipient, on a specific date and from a specific place. That letter was taken to the post office in a specific town on a certain day and year. The markings on the outside of the cover tell a complete story -- history in action.</p>

<p>Each of the letters in my collection have a story to tell, and I feel that I am the conservator of each letter while it is in my possession. After I am gone the next collector who owns that letter will be its conservator. The same may be said of the publicly held letters in special places like the Bentley Historical Library at the University of Michigan. These institutions are the conservators of letters and historical documents entrusted to them by the previous owners of those materials.</p>

<p>We are all saving history for future generations. I hope that the letters on my site, held by collectors and public institutions, will give the people who read and research them a deeper understanding of our predecessors. That knowledge and understanding can make the future a better place for us to all live in together. </p>

</div>	

app/views/about/genealogy.html.erb
<div class="container">
  <h2>List of Genealogy Clubs</h2>
  <p> <strong>County:Washtenaw</strong></p>
<p>Genealogy Society of Washtenaw County<br>
Education Center Auditorium St Joseph Mercy Hospital <br>
P.O.Box 7155 Ann Arbor MI 48107-7155 <br>
http://www.washtenawgenealogy.org/<br>
1:30 P.M.4th Sunday of the month<br>
</p>
<hr>
<p><strong>County:Michigan</strong>
<p>Michigan Genealogical Council<br>
New Place<br>
P.O Box 80953 Lansing MI 48908-0953<br>
http://www.mimgc.org/<br>
Various --see website</p>
<hr>
<p><strong>County:
Oakland County Genealogical Society</strong></p>

<p>P.O. Box 1094 Birmingham, MI 48012-1094<br>
ocgsmi.org info@ocgsmi.org<br>
Zoom/ check website</p>
</div>

app/views/about/history.html.erb
<div class="container">
  <h2>List of History Societies</h2>
  <p> <strong>County:Michigan</strong></p>
  <p>Historical Society of Michigan</p>
  <p>Historical Society of Michigan 5815 Executive Drive<br>Phone (517) 324-1828 | Fax (517) 324-4370<br>https://www.hsmichigan.org/</p>

<p>Please feel free to contact us at hsm@hsmichigan.org with your comments or suggestions.</p>
<hr>
<p><strong>County: La Posta : The Journal of American Postal History</strong></p>

<p>P.O. Box 6074 Fresericksburg, VA 22403<br>
www.lapostapub.com</p>

<p>Peter Martin Publisher and Editor</p>
</div>

app/views/about/import_data.html.erb
<div class="container">

  <h4> Import Stamps Club</h4> 
 
  <%= form_tag(import_about_index_path, :enctype =>"multipart/form-data") do %>

  <div class="row">
     <div class="field">
       <%#= label_tag :file %>
       <%#= file_field_tag :file,  :required => true  %>
     </div>
   </div>

  <div class="card" style="width: 45rem; padding-left: 10px;">  
  <p>
  <%= file_field_tag :file  %>
  </p>
  </div>
  
  <div class="form-group" style="padding-top: 20px">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Save</button> 
      <%#<button type="Reset" class="btn btn-secondary">Reset Form</button> %>
    </div>
  </div>

  <% end %>
</div>

app/views/about/national.html.erb
<div class="container">
  <h2>List of National Sites</h2>
  <p> <strong>Historical Society of Michigan</strong>
<p>Historical Society of Michigan 5815 Executive Drive <br>
Phone (517) 324-1828 | Fax (517) 324-4370<br>
https://www.hsmichigan.org/ </p>

<p>Please feel free to contact us at hsm@hsmichigan.org with your comments or suggestions.</p>
<hr>
<p><strong>La Posta : The Journal of American Postal History</strong></p>

<p>P.O. Box 6074 Fresericksburg, VA 22403<br>
www.lapostapub.com</p>

<p>Peter Martin Publisher and Editor</p>
</div>  

app/views/about/stamp.html.erb
<div class="container">
  <h2>List of Stamp Clubs</h2>
  <% s_list = Stamp.all.each do |s| %>
  <hr>
  <p><strong><%=s.cName%></strong></p>
  <p><%=s.pName %><br><%=s.Address%><br><%=s.MTimes%><br><%=s.Waddr %><br><%=s.Com%></p>
  
  <% end %>
</div> 